# Generated by Django 5.1 on 2024-10-03 17:37

import accounts.managers.user_manager
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('user_photo', models.ImageField(blank=True, default=None, upload_to='profile_photos/', verbose_name='Фото пользователя')),
                ('country', models.CharField(choices=[('other', 'Международный'), ('AZ', 'Азербайджан'), ('AM', 'Армения'), ('BY', 'Беларусь'), ('KZ', 'Казахстан'), ('KG', 'Кыргызстан'), ('MD', 'Молдова'), ('RU', 'Россия'), ('TJ', 'Таджикистан'), ('TM', 'Туркменистан'), ('UZ', 'Узбекистан')], max_length=5, verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=285, unique=True, verbose_name='Ваш юзернейм')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Ваш email')),
                ('telephone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True, verbose_name='Номер телефона')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('last_login', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата последнего входа')),
                ('user_role', models.CharField(choices=[('CUS', 'Клиент'), ('ADM', 'Админимстратор'), ('MOD', 'Модератор'), ('CNM', 'КонетнтМейкер'), ('DEV', 'Разработчик')], default='CUS', max_length=3, verbose_name='Роль | Пользователя')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Статус персонала')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('groups', models.ManyToManyField(blank=True, related_name='custom_user_set', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='custom_user_permissions_set', to='auth.permission')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
            managers=[
                ('objects', accounts.managers.user_manager.UserManager()),
            ],
        ),
    ]
