# Generated by Django 5.1 on 2024-09-14 15:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_last_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('description', models.TextField(verbose_name='Описание')),
                ('user_photo', models.ImageField(upload_to='profile_photos/', verbose_name='Фото пользователя')),
                ('country', models.CharField(choices=[('other', 'Международный'), ('AZ', 'Азербайджан'), ('AM', 'Армения'), ('BY', 'Беларусь'), ('KZ', 'Казахстан'), ('KG', 'Кыргызстан'), ('MD', 'Молдова'), ('RU', 'Россия'), ('TJ', 'Таджикистан'), ('TM', 'Туркменистан'), ('UZ', 'Узбекистан')], default='127.0.0.1', max_length=5, verbose_name='Страна')),
                ('language', models.CharField(choices=[('az', 'Азербайджанский'), ('am', 'Армянский'), ('by_be', 'Белорусский'), ('by_ru', 'Русский (Беларусь)'), ('kz_kk', 'Казахский'), ('kz_ru', 'Русский (Казахстан)'), ('kg_ky', 'Кыргызский'), ('kg_ru', 'Русский (Кыргызстан)'), ('md_ro', 'Молдавский (Румынский)'), ('ru_ru', 'Русский'), ('tj', 'Таджикский'), ('tm', 'Туркменский'), ('uz', 'Узбекский'), ('en', 'Английский (Международный)')], max_length=10, verbose_name='Язык')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
    ]
