# Generated by Django 5.1 on 2024-09-14 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='language',
        ),
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(choices=[('other', 'Международный'), ('AZ', 'Азербайджан'), ('AM', 'Армения'), ('BY', 'Беларусь'), ('KZ', 'Казахстан'), ('KG', 'Кыргызстан'), ('MD', 'Молдова'), ('RU', 'Россия'), ('TJ', 'Таджикистан'), ('TM', 'Туркменистан'), ('UZ', 'Узбекистан')], max_length=5, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_photo',
            field=models.ImageField(blank=True, default=None, upload_to='profile_photos/', verbose_name='Фото пользователя'),
        ),
    ]
