# Generated by Django 5.1 on 2024-10-11 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='is_private',
            field=models.BooleanField(choices=[(True, 'Да'), (False, 'Нет')], default=False, verbose_name='Сделать видео приватным'),
        ),
        migrations.AddField(
            model_name='content',
            name='preview_image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='preview/$Y/%m/%d/', verbose_name='Превью'),
        ),
    ]
