# Generated by Django 5.1 on 2024-09-06 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='categories_content',
            field=models.ManyToManyField(related_name='categories_content', to='content.category'),
        ),
    ]
