# Generated by Django 5.1 on 2024-09-11 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_content_author_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='categories_content',
            field=models.ManyToManyField(blank=True, null=True, related_name='categories_content', to='content.category'),
        ),
    ]
